### ISSUE TITLE
A mode for repair possibilities without Mutation

### ISSUE THREAD

**Issue by sohah** [sohah/ContractDR#2]
A separate mode is needed apart from mutation that would run on already faulty spec to try to repair different places of the specification.

**Comment by vaibhavbsharma** [comment]
I dont understand what this issue is about.

**Comment by sohah** [comment]
This is about trying to use the repair wrapping, that already exists as part of the mutation, as a different component that can possibly be invoked seperately.

For example,

Given a spec: 
a and b

we can do 

repair(a) and b
a and repair(b)
repair(a and b)

note that this has happened on the original spec, without mutating it. This is slightly different from the current setup that uses the repair wrapping as part of the mutants generation.

This extension is useful to allow us to possibly run on already faulty spec. In GPCA there are a couple of already faulty specs that we wish to try to repair.

**Comment by vaibhavbsharma** [comment]
Alright, I agree we need to extend mutation to support this.

**Comment by vaibhavbsharma** [comment]
I've just pushed a change for this in. You can now make the mutation generate "repair mutants" by turning on a "repairMutantsOnly" flag in your JPF config. This flag is only effective when you've also turned on "mutationEnabled". Please give it a shot and let me know what you think.
